### ISSUE TITLE
Problem Change wireframe form Quadrangulate To Triangulate!

### ISSUE THREAD

**Issue by MostFull** [f3d-app/f3d#941] opened 2023-08-08 17:40 UTC
Why does the wireframe appear in the form of Triangulate, even though it is Quadrangulate?
![Screenshot 2023-08-08 203156](https://github.com/f3d-app/f3d/assets/10875710/7b6c365e-89a7-4d0c-b533-efa17a2e354c)

**Comment by mwestphal** [comment] 2023-08-09 17:51
It is caused either by:

- your software export to .fbx
- assimp importing the fbx
- f3d usage of assimp

Please share the .fbx file

**Comment by mwestphal** [comment] 2023-08-09 17:52
@Meakk

**Comment by MostFull** [comment] 2023-08-09 19:40
Prefer this project file
[Diwan Old Sanaa.zip](https://github.com/f3d-app/f3d/files/12306330/Diwan.Old.Sanaa.zip)

**Comment by Meakk** [comment] 2023-08-09 20:24
In f3d, we are taking any cell size given by assimp:
https://github.com/f3d-app/f3d/blob/b438e86a70bbb7416e130e74f9b2133feafda45b/plugins/assimp/module/vtkF3DAssimpImporter.cxx#L479

**Comment by mwestphal** [comment] 2023-08-10 08:10
I'm not enterely sure if this is caused by assimp or your software but it is not caused by F3D. Which software are you exporting from ?

**Comment by MostFull** [comment] 2023-08-10 09:55
Exporting by Maya and Blender, any model wireframe Quadrangulate, F3D converts it to TriangulateIt

**Comment by mwestphal** [comment] 2023-09-17 13:55
Closing this as this seems to not be caused by F3D, feel free to reopen @MostFull

**Closed by mwestphal** 2023-09-17 13:55 UTC
