### ISSUE TITLE
Show Bone in F3D

### ISSUE THREAD

**Issue by MostFull** [f3d-app/f3d#1238] opened 2024-01-30 15:52 UTC
Why is the bone not shown in F3D?  For example, I have fbx files, which are movements. When I display them in F3D, nothing is displayed!

**Comment by mwestphal** [comment] 2024-01-30 15:53
duplicate of #56

**Closed by mwestphal** 2024-01-30 15:53 UTC

**Comment by mwestphal** [comment] 2024-01-30 15:58
To answer your questions specifcally, the bone is not read as a geometry so it cannot be shown. But it should, see the issue I linked.

**Comment by mwestphal** [comment] 2025-01-24 07:57
Added for glTF in https://github.com/f3d-app/f3d/pull/1796
