### ISSUE TITLE
Add Polygon&Vertex Count

### ISSUE THREAD

**Issue by MostFull** [f3d-app/f3d#936] opened 2023-08-01 08:52 UTC
Add statues Polygon Count and Vertex Count
Like this image
![Blender-How-to-show-Polygon-Count-for-Selected-Object-and-Scene-cgian-702x336](https://github.com/f3d-app/f3d/assets/10875710/0459d19b-fc36-4fda-902b-94479adab1f5)

**Comment by mwestphal** [comment] 2023-08-01 08:53
Hi @MostFull 

You can display the metadata by pressing `M`, however it is not available for all formats.

**Comment by MostFull** [comment] 2023-08-01 08:56
Thank you for your reply. How do I make it available? Is there a solution?

في الثلاثاء، ١ أغسطس ٢٠٢٣, ١١:٥٤ ص Mathieu Westphal <
***@***.***> كتب:

**Comment by mwestphal** [comment] 2023-08-01 08:59
Please share an example file :)

**Comment by MostFull** [comment] 2023-08-01 09:09
Can I enable metadata for all formats? Or is this a programming error and
you will fix it?

في الثلاثاء، ١ أغسطس ٢٠٢٣, ١١:٥٩ ص Mathieu Westphal <
***@***.***> كتب:

**Comment by mwestphal** [comment] 2023-08-01 11:23
> Can I enable metadata for all formats

No this is not implemented yet.

> is this a programming error and you will fix it?

Not an error, a missing feature. It will be adressed once #653 is adressed.

**Comment by MostFull** [comment] 2023-08-01 11:32
Thanks 😊

**Comment by mwestphal** [comment] 2023-08-04 06:24
BTW its a duplicate of #222

**Closed by mwestphal** 2023-08-04 06:24 UTC
