### ISSUE TITLE
specular highlights work the wrong way (Wavefront Material Library)

### ISSUE THREAD

**Issue by HalanoSiblee** [f3d-app/f3d#523] opened 2022-12-06 09:17 UTC
F3D render wavefront .obj specular highlight in negative way
for example 

> newmtl Weapon
_**Ns 250.000000**_
Ka 1.000000 1.000000 1.000000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.450000
d 1.000000
illum 2
map_Kd  Weapon.png

Ns: defines the focus of specular highlights
F3D swap it less specular in mtl more in render !

**Comment by HalanoSiblee** [comment] 2022-12-07 23:11
What is the point of sharing the wavefront model i made my issue clear
F3D add more specular lights on surfaces while wavefront material lib say Ns = 0.0
it working the wrong way.
however here the model.
[SimpleWeapon.zip](https://github.com/f3d-app/f3d/files/10180742/SimpleWeapon.zip)

**Comment by snoyer** [comment] 2022-12-08 04:11
Provided sample with stronger red specular color:
```
newmtl Weapon
Ns 0.000000
Ka 1.000000 1.000000 1.000000
Ks 5.000000 0.000000 0.000000
Ke 0.000000 0.000000 0.000000
Ni 1.450000
d 1.000000
illum 2
map_Kd Weapon.png
```
![weapon-ns0](https://user-images.githubusercontent.com/489715/206353520-f697ce54-7099-4c89-9ce3-36a5f0478cbd.png)


```
newmtl Weapon
Ns 1000.000000
Ka 1.000000 1.000000 1.000000
Ks 5.000000 0.000000 0.000000
Ke 0.000000 0.000000 0.000000
Ni 1.450000
d 1.000000
illum 2
map_Kd Weapon.png
```
![weapon-ns1000](https://user-images.githubusercontent.com/489715/206353500-b9a1c462-9a71-44f1-b530-616975ecec48.png)




For reference, according to [Paul Bourke](http://paulbourke.net/dataformats/mtl/):
> Ns exponent
> Specifies the specular exponent for the current material.  This defines the focus of the specular highlight.
> "exponent" is the value for the specular exponent.  **A high exponent results in a tight, concentrated highlight**.  Ns values normally range from 0 to 1000. 

visual example from [polycount.com](https://polycount.com/discussion/comment/1211905/#Comment_1211905):
![example](https://developer.valvesoftware.com/w/images/f/f5/Specvsexponentinphong2os.jpg)

visual example from [scratchapixel.com](https://www.scratchapixel.com/lessons/3d-basic-rendering/phong-shader-BRDF):
![example](https://www.scratchapixel.com/images/upload/shading-intro2/shad2-phong.png)

**Comment by mwestphal** [comment] 2022-12-08 06:47
@Meakk wdyt ?

**Comment by Meakk** [comment] 2022-12-08 09:36
> What is the point of sharing the wavefront model i made my issue clear

In order to reproduce the problem.  
You also deleted all the useful content we are asking to help you solving your issue (F3D version, VTK version, operating system, modules...)

As @snoyer pointed out, the `Ns` parameter seems to represent the area of the specular lobe, not its intensity.  
And looking at his screenshots, it seems to work as expected.  
Also, this kind of material is legacy and not using the PBR workflow (metallic/roughness).

I'm closing this because I don't think this is an issue. If you disagree, feel free to reopen it with a better description and analysis of the problem.

**Closed by Meakk** 2022-12-08 09:36 UTC
Labels: bug, VTK

**Comment by HalanoSiblee** [comment] 2022-12-08 09:39
Windows 3d Viewer when Ns parameter = 1000
![Capture](https://user-images.githubusercontent.com/70325026/206411541-6124afd4-a132-4f9f-9227-27391d9867e4.PNG)
F3D when Ns Parameter = 1000
![2022-12-08-093032_1366x768_scrot](https://user-images.githubusercontent.com/70325026/206411638-01fbf38d-29d0-499d-be7e-822059b824fe.png)
F3D when Ns Parameter = 0.0
![2022-12-08-093540_1366x768_scrot](https://user-images.githubusercontent.com/70325026/206411725-68976d41-ceac-4fe6-914a-9297deefc41c.png)
**Thanks for help**

**Comment by Meakk** [comment] 2022-12-08 13:22
In the Windows 3d viewer, they are using an HDRI which emphasizes the glossy effect of a high specular area coefficient.  
F3D is not supporting HDRI for non-PBR materials yet.  
Please take a look at @snoyer screenshots to better understand what's going on.

**Comment by Meakk** [comment] 2022-12-08 13:32
I filed a dedicated issue here: https://github.com/f3d-app/f3d/issues/533
