### ISSUE TITLE
Fbx View is not working

### ISSUE THREAD

**Issue by hgeunkim** [f3d-app/f3d#1490] opened 2024-06-27 02:13 UTC
**Describe the bug**
I used f3d app and its python binding for mixamo
[https://www.mixamo.com/#/?page=1&type=Motion%2CMotionPack](url)
But it is not working with latest mixamo fbx.

![image](https://github.com/f3d-app/f3d/assets/101172782/ff461c6c-bf30-43ba-9994-ad03a7747acb)
![image](https://github.com/f3d-app/f3d/assets/101172782/c4da45c0-3c8d-4b44-a62a-2f04d25fe9fa)

**To Reproduce**
 1. Download the attached file and unzip.
[walking_fbx.zip](https://github.com/user-attachments/files/16006730/walking_fbx.zip)

 2. Drop down 2 files on f3d app and play animation.

 3. One is shown properly, but another is not.

**Expected behavior**
I hope to show latest mixamo fbx in a proper way.

**System Information:**
 - OS: Windows 10
 - GPU and GPU driver: NVIDIA GeForce RTX 3080, 31.0.15.3623

**F3D Information**
Paste the content of `f3d --version`:
F3D 2.4.0

F3D - A fast and minimalist 3D viewer
Version: 2.4.0.
Build date: 2024-04-03 14:39:50.
Build system: Windows 64-bits.
Compiler: MSVC 19.38.33135.0.
External rendering module: ON.
Raytracing module: ON.
VTK version: 9.3.0-2200-g1312f8a726 (date: 20240312).
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2024 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.

**Additional context**

**Comment by mwestphal** [comment] 2024-06-27 05:53
Duplicate of this: https://github.com/f3d-app/f3d/issues/414

We have a fix to try as described here tough: https://github.com/assimp/assimp/issues/4620#issuecomment-2186209971

**Closed by mwestphal** 2024-06-27 05:53 UTC

**Comment by hgeunkim** [comment] 2024-06-27 07:01
Thank you for reply.
As mentioned in the issue you left, is there a way to set AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS in the f3d app and python binding?

**Comment by mwestphal** [comment] 2024-06-27 08:53
I'm afraid not, but we will try this fix for the next release and see if it improve the situation with assimp.
