### ISSUE TITLE
My glb and .gltf files no longer work.

### ISSUE THREAD

**Issue by GlacierFox** [f3d-app/f3d#1220] opened 2024-01-25 14:36 UTC
**Describe the bug**
My glb and .gltf files no longer work. The file name loads into the viewport but it's invisible. Tried the same file in USD and OBJ formats and they work.
**To Reproduce**
Drag file into the F3D window.

**Expected behavior**
For the file to load.

**System Information:**
 - OS: Tried on both Windows and Linux (Windows 11 and RHEL 9)
 - GPU and GPU driver: Both Intel and Nvidia.

**F3D Information**
2.3.0

**Comment by GlacierFox** [comment] 2024-01-25 14:47
> Hi @GlacierFox
> 
> Please share your files

Apologies, I missed those out! Here's a selection of the same model in different formats. They all work apart from the gltf and glb files.

[R-20.zip](https://github.com/f3d-app/f3d/files/14053541/R-20.zip)

**Comment by mwestphal** [comment] 2024-01-25 15:24
If you run with `--verbose` you will see:

```
Loading 3D scene: /home/glow/data/tmp/R-20.glb

ERROR: In vtkGLTFDocumentLoaderInternals.cxx, line 1308
vtkGLTFDocumentLoader (0x557b99a388d0): glTF extension KHR_texture_transform is required in this model, but not supported by this loader. Aborting


ERROR: In vtkGLTFImporter.cxx, line 387
vtkGLTFImporter (0x557b9916c140): Error loading model metadata


ERROR: In vtkGLTFImporter.cxx, line 796
vtkGLTFImporter (0x557b9916c140): The GLTF model is nullptr, aborting.


No animations available in this file

ERROR: In vtkGLTFImporter.cxx, line 796
vtkGLTFImporter (0x557b9916c140): The GLTF model is nullptr, aborting.


ERROR: In vtkGLTFImporter.cxx, line 796
vtkGLTFImporter (0x557b9916c140): The GLTF model is nullptr, aborting.


Animation(s) time range is: [inf, -inf].
ERROR: In vtkGLTFImporter.cxx, line 581
vtkGLTFImporter (0x557b9916c140): The GLTF model is nullptr, aborting.

```

So this issue is a duplicate of #608 

However you mention: 

> My glb and .gltf files no longer work. 

Which version of F3D supported your data ? I doubt this extension was ever supported.

**Comment by mwestphal** [comment] 2024-01-25 16:30
Thanks for checking, closing as duplicate

**Closed by mwestphal** 2024-01-25 16:30 UTC
