### ISSUE TITLE
No UI text on Linux (AUR f3d-bin) when no file is loaded

### ISSUE THREAD

**Issue by epsimatic** [f3d-app/f3d#752] opened 2023-04-22 03:05 UTC
**Describe the bug**
When opening f3d with no files, Linux & macOS versions show different UIs. 
On macOS, it displays help text and XYZ gizmo; on Linux, it's blank.

| Linux | Mac |
|------|-----|
| ![linux-text](https://user-images.githubusercontent.com/1821846/233758244-4da46c75-cbd3-4e01-b99b-5f94c661e843.png) | ![mac-text](https://user-images.githubusercontent.com/1821846/233758249-beb921ba-b3b5-43ea-b764-16e782240398.png) |

**To Reproduce**
Steps to reproduce the behaviour:

1. Start `f3d` on Linux with no arguments
2. Start `f3d` on Mac with no arguments 
3. Observe the difference

**Expected behaviour**

Linux and Mac versions show the same behaviour with a help text. 

The help text is valid for both platforms, as the Linux version accepts drag-and-drop files too.

You might show the XYZ gizmo on all platforms too because it hints about the nature of the app

**System Information:**
 - OS: macOS 13.3.1 (22E261) / EndeavourOS latest

**F3D Information**
Paste the content of `f3d --version`:

```
F3D 2.0.0

F3D - A fast and minimalist 3D viewer
Version: 2.0.0.
Build date: 2023-04-20 17:06:45.
Build system: Darwin 64-bits.
Compiler: AppleClang 14.0.0.14000029.
External rendering module: ON.
Raytracing module: OFF.
VTK version: 9.2.6 (build 20230224).
```

**Additional context**

**Comment by mwestphal** [comment] 2023-04-22 07:28
> on Linux, it's blank.

That is definitely unexpected, how di you install F3D in that case ?

**Comment by mwestphal** [comment] 2023-04-22 09:02
f3d-bin AUR is not managed by the F3D team, please report the issue on the aur package.

FYI even f3d-git may be broken, we need to update it.

FYI @kylosus

**Comment by epsimatic** [comment] 2023-04-22 09:03
Sorry, my bad. It was Arch Linux AUR package `f3d-bin`. 

I was in hurry and didn't wait for `community/f3d` package update, and didn't use your official flatpak.

I've tried `community/f3d` (which is updated now) and it shows no UI either. 

Now I'm trying to install Flatpak package and check it

**Comment by mwestphal** [comment] 2023-04-22 09:05
> I've tried community/f3d (which is updated now) and it shows no UI either.

We reworked the configuration files logic, so an update is probably needed  (@sventaro)

**Comment by mwestphal** [comment] 2023-04-22 09:27
@epsimatic : I just update the f3d-git package, if that helps.

**Comment by kylosus** [comment] 2023-04-22 09:30
The text seems to disappear when an empty `config.d` directory is present in `/etc/f3d/`, which the f3d-bin package creates for convenience. I suppose the package not create this directory? I had assumed all config dirs would be read in order and the packaged configs were meant to be examples/defaults, but the documentation says F3D only uses the first one found.

**Comment by mwestphal** [comment] 2023-04-22 09:47
> the documentation says F3D only uses the first one found.

Yes, this is correct. This could be changed but it involve a lot of work and I could not really justify it.

> The text seems to disappear when an empty config.d directory is present in /etc/f3d/, which the f3d-bin package creates for convenience.

I've been looking at the package and it needs to be updated with all the recent changes to configuration files logic.

**Comment by epsimatic** [comment] 2023-04-22 10:12
To summarize the issue:

- Arch `community/f3d` : **config broken,** no UI
- `AUR/f3d-bin` (not managed by you) : config broken
- `AUR/f3d-git` : config valid, UI available after https://github.com/f3d-app/f3d/issues/752#issuecomment-1518577091
- Flatpak : **config broken,** no UI
- macOS downloadable .dmg : config valid, UI available

Maybe it's reasonable to reopen the issue until `community/f3d`and Flatpak packages are fixed?

> Why not just grabbing the portable tarbal ?

It's a worse decision for the long run — no updates, no dependency management, etc.

**Comment by kylosus** [comment] 2023-04-22 10:26
`AUR/f3d-bin` is updated now.

**Comment by mwestphal** [comment] 2023-04-22 10:32
Thanks a lot @kylosus 

> Arch community/f3d : config broken, no UI

Not managed by the F3D team either, I've logged an issue on arch bugreports system, I hope @svenstaro can take a look soon


> Flatpak : config broken, no UI

Not managed by the F3D team either, I hope @kevinsmia1939 can take a look, no idea how to report an issue there.

> reopen the issue until community/f3dand Flatpak packages are fixed?

I'd rather not since this is out of the hands of the F3D team and developers.

**Comment by kevinsmia1939** [comment] 2023-04-22 20:25
@mwestphal 
I'm working on the update.
The issue can be report here: https://github.com/flathub/io.github.f3d_app.f3d/issues

**Comment by svenstaro** [comment] 2023-04-23 00:44
Arch package should now be fixed in rel-3.

**Comment by mwestphal** [comment] 2023-04-23 05:10
@svenstaro tested and confirmed to work perfectly now ! Thanks !

**Closed** 2023-04-23 09:43 UTC
