### ISSUE TITLE
OBJ files from 3D scans display very poorly, I lack proper wording to describe the issue (see image)

### ISSUE THREAD

**Issue by Toughbook-CFC2** [f3d-app/f3d#1067] opened 2023-11-13 01:00 UTC
![F3D_Issue](https://github.com/f3d-app/f3d/assets/74775077/4202ce06-9875-4ab4-8131-0ff0b127180b)
**Describe the bug**
STL files I create with openscad display fine and can be viewed without issue. 
But when opening OBJ files created with 3D scanning, they display some kind of weird shadowing. 
Large parts are completely black and the visuals change dramatically when shifting the camera. 
I don't have the appropriate vocabulary to describe what exactly is happening, but I played around with 
the settings and could not get rid of it and so far it also hasn't changed with updates. Please see the attached screenshot.
**To Reproduce**
Open an OBJ file

**Expected behavior**
The file displays without dark spots and shadows
**System Information:**
 - OS: Arch Linux 
 - GPU and GPU driver: Intel i5-2520m iGPU

**F3D Information**
Paste the content of `f3d --version`: 2.2.1

**Comment by Meakk** [comment] 2023-11-13 05:56
Can you share the file?

**Comment by Toughbook-CFC2** [comment] 2023-11-13 17:28
Sure, I can't share this file type here though, so I hope this 'file . io' link does the trick. https://file.io/zmjcKXKrU8nX

**Comment by mwestphal** [comment] 2023-11-14 07:47
Duplicate of https://github.com/f3d-app/f3d/issues/842, already fixed in VTK.

Use F3D binary release (https://f3d.app/doc/user/INSTALLATION.html) until ArchLinux update their VTK package to 9.3.0

![a](https://github.com/f3d-app/f3d/assets/3129530/ed2a8ca3-782b-48ad-aedb-1b03e4df5b82)

FYI @antonio-rojas

**Closed by mwestphal** 2023-11-14 07:47 UTC
