### ISSUE TITLE
Huge memory leak when files are created

### ISSUE THREAD

**Issue by Alumx** [f3d-app/f3d#470] opened 2022-11-03 14:19 UTC
**Describe the bug**
I don't know why but suddenly f3d is spiking with huge RAM and disk usage every time new files are created (eg: exporting frames, unzipping folder, etc...)
![image](https://user-images.githubusercontent.com/64172068/199743369-e7ee1e13-867e-4b69-882a-4b1e755d79d0.png)
![image](https://user-images.githubusercontent.com/64172068/199743391-eb8d7bbd-646a-4dc7-b2a5-62647dc5f47c.png)

**To Reproduce**
 1. Get a zip file with a lot of files inside
 2. unzip it
 3. f3d lags whole computer down

**System Information:**
 - OS: Win Windows-10-10.0.19044-SP0 64 Bits
 - GPU and GPU driver: NVIDIA GeForce RTX 3080/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 522.30 (Release date: 10/18/2022)

**F3D Information**
f3d 1.3.1

F3D - A fast and minimalist 3D viewer
Version: 1.3.1.
Build date: 2022-09-07 10:09:04.
Build system: Windows AMD64.
Compiler: MSVC 19.33.31629.0.
External rendering module: ON.
Raytracing module: OFF.
Exodus module: ON.
OpenCASCADE module: 7.6.0 (no metadata).
Assimp module: 5.1.0.
Alembic module: 1.8.3.
VTK version: 9.2.20220821 (build 20220821).
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2022 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.

**Additional context**
This didn't happen before, no changes happened in my computer between then and now ( windows updates or softwares)

**Comment by Meakk** [comment] 2022-11-03 14:37
You probably already know it, but it's the thumbnail generation. Once the thumbnails are generated, the memory consumption and cpu load will stop.  
Can you give additional info about the files? (e.g. extension, file size, number of vertices/triangles)

**Comment by Meakk** [comment] 2022-11-03 14:38
Probably related: #300

**Comment by Alumx** [comment] 2022-11-03 14:53
> You probably already know it, but it's the thumbnail generation. Once the thumbnails are generated, the memory consumption and cpu load will stop. Can you give additional info about the files? (e.g. extension, file size, number of vertices/triangles)

It feels like f3d tries to read all the files
in both cases where it almost halted my computer none of the files were 3D
case 1: extracting blender zip folder (https://builder.blender.org/download/daily/)
case 2: rendering png image sequence from davinci

**Comment by Alumx** [comment] 2022-11-03 14:53
> You probably already know it, but it's the thumbnail generation. Once the thumbnails are generated, the memory consumption and cpu load will stop. Can you give additional info about the files? (e.g. extension, file size, number of vertices/triangles)

It feels like f3d tries to read all the files
in both cases where it almost halted my computer none of the files were 3D
case 1: extracting blender zip folder (https://builder.blender.org/download/daily/)
case 2: rendering png image sequence from davinci

**Comment by Meakk** [comment] 2022-11-03 15:21
Thank you @Alumx we'll investigate

**Comment by mwestphal** [comment] 2023-02-13 07:41
@Alumx I can't reproduce so far, using F3D 1.3.1 release on Windows.

Steps :
- Remove all previously installed F3D and F3D Shell Extensions
- Remove all cache thumbnails using Windows Disk Cleanup Utilities
- Install F3D from 1.3.1 binary release installer, make sure thumbnail checkbox is checked
- Navigate to a folder containing 3D data. Thumbnails are generated as expected (see below for more info)
- Download Blender Zip folder
- Navigate to it
- No F3D activity in the task manager (althgouh it can be fast and unseen)


About the way thumbnails are generated by Windows, I've remarked a few things:
1. Windows requests thumbnails only for layout type that request them. eg "Details" mode will not request any thumbnails
2. It looks like thumbnails are generated one by one, I've never had multiple F3D process, only one, which can take some memory but cant be that big since we fixed #300 
3. Windows will request thumbnails only for visible thumbnails, not hidden one.

So I think there must be something wrong with @Alumx setup. Either a previous F3D shell extension was not correctly removed (this was an issue with 1.2.1) or Windows is doing crazy things.

Could you try and see if you reproduce the behavior I'm describing ?

That being said, we do have an idea to improve thumbnail generation further. Indeed, it looks like the thumbnail provided do not check if F3D is able to open a file before trying to run F3D to open it. We could easily add a check for that, but I'm not enterely sure this will fix your issue.


Could you also test on your side @Meakk ?

Any inputs @jpouderoux ?
-

**Comment by mwestphal** [comment] 2023-02-13 08:30
So I took a deeper look and I can confirm that file extension is already considered for the thumbnailer, in `winshellext/F3DShellExtension.cxx.in`

```
//------------------------------------------------------------------------------
// Register the COM server and the f3d thumbnail handler.
STDAPI DllRegisterServer()
{
  wchar_t szModuleName[MAX_PATH];
  if (GetModuleFileName(g_hInst, szModuleName, ARRAYSIZE(szModuleName)) == 0)
  {
    return HRESULT_FROM_WIN32(GetLastError());
  }

  // Register the component.
  HRESULT hr = RegisterInprocServer(
    szModuleName, CLSID_F3DThumbnailProvider, L"F3DShellExtension.F3DThumbnailProvider Class");
  if (!SUCCEEDED(hr))
  {
    return hr; 
  }
  // Register the thumbnail handler. The thumbnail handler is associated
  // with the f3d file class.
  for (auto ext : { @F3D_SUPPORTED_EXTENSIONS_INITIALIZER_LIST@ })
  {
    hr |= RegisterShellExtThumbnailHandler(ext, CLSID_F3DThumbnailProvider);
  }
  if (SUCCEEDED(hr))
  {
    // Invalidate the thumbnail cache.
    SHChangeNotify(SHCNE_ASSOCCHANGED, SHCNF_IDLIST, NULL, NULL);
  }

  return hr; 
}

//------------------------------------------------------------------------------
// Unregister the COM server and the f3d thumbnail handler.
STDAPI DllUnregisterServer()
{
  wchar_t szModuleName[MAX_PATH];
  if (GetModuleFileName(g_hInst, szModuleName, ARRAYSIZE(szModuleName)) == 0)
  {
    return HRESULT_FROM_WIN32(GetLastError());
  }

  // Unregister the component.
  HRESULT hr = UnregisterInprocServer(CLSID_F3DThumbnailProvider);
  if (SUCCEEDED(hr))
  {
    // Unregister the thumbnail handler.
    for (auto ext : { @F3D_SUPPORTED_EXTENSIONS_INITIALIZER_LIST@ })
    {   
      hr |= UnregisterShellExtThumbnailHandler(ext);
    }   
  }

  return hr; 
}

```

**Comment by mwestphal** [comment] 2023-02-13 08:33
@Alumx please test again, ideally with the nightly and let us know how it goes. 

There is an issue in the nightly right now: https://github.com/f3d-app/f3d/issues/628 but it should not prevent you to test the thumbnails.

**Comment by mwestphal** [comment] 2023-02-13 18:09
@Meakk

**Comment by mwestphal** [comment] 2023-02-16 07:25
@Meakk assigning to you so that you test it yourself at some point.

**Comment by Meakk** [comment] 2023-02-16 14:20
I tested it and cannot reproduce.

**Comment by mwestphal** [comment] 2023-02-16 14:27
Thanks, closing. @Alumx let us know if you still have issues.

**Comment by Kettenotter** [comment] 2023-02-18 18:32
I also had some huuuuge memory leaks. 150GB+.
I uninstalled, reinstalled the shell extension. And cleaned the thumbnails. And it kinda worked. But still had sometimes instances of f3d which would just hold onto memory and never exit.
Deinstalled windows 3D viewer and some stuff and now I have only reliable memory leak:
when I restart windows and there are 3D files on the desktop. Then it will launch for every file a instance of f3d which will take up ~8gb of memory and never release it until I shut it down with task manager.


<img width="839" alt="perfmon_539" src="https://user-images.githubusercontent.com/32515271/219881723-87357438-4b23-49a9-a848-f079bf1ef6d2.png">

**Comment by mwestphal** [comment] 2023-02-19 09:15
> Then it will launch for every file a instance of f3d which will take up ~8gb of memory and never release it until I shut it down with task manager.

Which version of F3D are you testing this with 1.3.1 ?

When you say "Every File", you mean every 3D file, is that correct ?

What size of these files ?

TBH I did not check on the desktop, maybe this is specific to that, I will check.

**Comment by Kettenotter** [comment] 2023-02-20 09:54
It happened both wirh 1.3.1 and the nightly build.
Stopped happening, but after some testing I could reproduce it again.
It was because of an interaction with **Windows 3D viewer**. After I reinstalled it the behavior came back. Sometimes it would launch one or multiple instances of f3d and then never release them. They also would grow in memory size even though I have nothing open. (Closed file explorer and so on)

Here is how it looks:
![Taskmgr_556](https://user-images.githubusercontent.com/32515271/220067560-1aa70ed9-6123-46c5-8d2b-fc740d7a9a8a.gif)

It only happens sometimes and then it seems to stop until the next restart.
Perhaps someone else can test it:
https://www.microsoft.com/store/productId/9NBLGGH42THS
Most reliable it would happen when I search for *.obj files on my computer. Not sure if it has anything todo with the details view on the side but it might.

**Comment by mwestphal** [comment] 2023-02-20 12:35
I have not been able to reproduce with 3D viewer installed and search for obj. I sometimes see multiples (3/4) instances of F3D opened at the same time but it stabilize quite fast. Never seen memory explosion but tbh it could happen if there is a file that makes F3D hangs and leaks.

One thing to consider is that I'm using not updated windows 10 so maybe only present with the last version of 3D viewer somehow ?

What size of these files ? Could you share a folder of files to search into in order to reproduce the issue ?

Do you have thumbnails generation with only 3D viewer installed for .obj files ?

**Comment by mwestphal** [comment] 2023-03-22 07:47
Without inputs from @Kettenotter , Ill go ahead and close this. Pleas reopen if needed.

**Closed by mwestphal** 2023-03-22 07:47 UTC
Labels: type:bug, priority:P0
