### ISSUE TITLE
F3D is unable to properly display *.glb model

### ISSUE THREAD

**Issue by cryptosebek** [f3d-app/f3d#1175] opened 2024-01-16 09:52 UTC
F3D is unable to properly display *.glb model

 1. Try to open *.glb file: [roger_rabbit.zip](https://github.com/f3d-app/f3d/files/13948155/roger_rabbit.zip)
 2. Observe empty scene: ![image](https://github.com/f3d-app/f3d/assets/93789460/edc5264e-740a-4242-b470-bf837d7897c2)

**System Information:**
 - OS: Windows
 - GPU: RTX 3060

**F3D Information**
Version: 2.2.1.
Build system: Windows 64-bits.
Compiler: MSVC 19.35.32217.1.
External rendering module: ON.
Raytracing module: OFF.
VTK version: 9.3.0.rc0-514-g1a5445687f (date: 20230922).

**Comment by mwestphal** [comment] 2024-01-16 09:56
```
ERROR: In vtkGLTFDocumentLoaderInternals.cxx, line 1308
vtkGLTFDocumentLoader (0x55d351e829e0): glTF extension KHR_materials_pbrSpecularGlossiness is required in this model, but not supported by this loader. Aborting


ERROR: In vtkGLTFReader.cxx, line 744
vtkGLTFReader (0x55d3515d9140): Error loading model metadata from file /home/glow/data/tmp/roger_rabbit.glb


ERROR: In vtkExecutive.cxx, line 730
vtkCompositeDataPipeline (0x55d351e82070): Algorithm vtkGLTFReader (0x55d3515d9140) returned failure for request: vtkInformation (0x55d351e81170)
  Debug: Off
  Modified Time: 10954
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_INFORMATION
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0




Loading 3D geometry: /home/glow/data/tmp/roger_rabbit.glb

ERROR: In vtkGLTFDocumentLoader.cxx, line 937
vtkGLTFDocumentLoader (0x55d351e829e0): Error loading model data: metadata was not loaded


ERROR: In vtkGLTFReader.cxx, line 858
vtkGLTFReader (0x55d3515d9140): Error loading model data


ERROR: In vtkExecutive.cxx, line 730
vtkCompositeDataPipeline (0x55d351e82070): Algorithm vtkGLTFReader (0x55d3515d9140) returned failure for request: vtkInformation (0x55d351ee4a20)
  Debug: Off
  Modified Time: 603010
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

```

**Comment by mwestphal** [comment] 2024-01-16 09:56
Duplicate of https://github.com/f3d-app/f3d/issues/943, closing

**Closed by mwestphal** 2024-01-16 09:56 UTC

**Comment by cryptosebek** [comment] 2024-01-19 19:47
[Here is possible workaround for this.](https://github.com/f3d-app/f3d/issues/943#issuecomment-1901010261)
