### ISSUE TITLE
OBJ texture black with archlinux VTK pacakage

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#842] opened 2023-06-04 08:10 UTC
**Describe the bug**
OBJ texture do not render as expected when building against archlinux VTK package

**To Reproduce**
 1. Build F3D against archlinux VTK package: `vtk 9.2.6-6`
 2. `./bin/f3d ../src/testing/data/world.obj`

![TestOBJImporter](https://github.com/f3d-app/f3d/assets/3129530/1991e987-a3fc-4a5b-8cb3-4f457d6e2bfb)

**Expected behavior**

![TestOBJImporter](https://github.com/f3d-app/f3d/assets/3129530/0ea21705-43db-4d19-8ff9-a0283f785356)

**System Information:**
 - OS: ArchLInux
 - GPU and GPU driver: nvidia  530.41.03

**F3D Information**
Paste the content of `f3d --version`:

```
[glow@arch ~/dev/f3d/f3d/build]$ ./bin/f3d --version
F3D 2.0.0

F3D - A fast and minimalist 3D viewer
Version: 2.0.0-87-ga1a789ae.
Build date: 2023-06-04 08:04:53.
Build system: Linux 64-bits.
Compiler: GNU 13.1.1.
External rendering module: OFF.
Raytracing module: OFF.
VTK version: 9.2.6.
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2023 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.

```

**Additional context**

Not sure it actually matters, but I dont see a reason for this not to work with VTK 9.2.6 whatever the compilation option may be, so investigating it to understand why it is doing that may be worthwile.

**Comment by Meakk** [comment] 2023-06-04 08:58
I reproduced this issue yesterday with an older version of VTK

**Comment by snoyer** [comment] 2023-06-04 09:09
Same with Fedora's VTK `9.2.5`

**Comment by mwestphal** [comment] 2023-06-04 17:43
If that is related to the version of VTK, how can it work in the CI ? I need to check on that.

**Comment by Meakk** [comment] 2023-06-07 21:47
I've run it in apitrace, the pixels are blacks because the RGB values are NaN.  
The texture is properly bound to the texture unit.

![2023-06-07-234554_2893x1483](https://github.com/f3d-app/f3d/assets/6069752/f1a049f0-90fc-4597-941a-14ad898d354c)

**Comment by Meakk** [comment] 2023-06-07 21:58
The problem is in VTK and has already been fixed here: https://github.com/Kitware/VTK/commit/ef1cca17af2eba26fa6ef6d45ec0bbd1be6aabb7

**Comment by Meakk** [comment] 2023-06-07 22:06
I just built a VTK master and I confirm the issue is fixed. Closing the issue.

**Closed by Meakk** 2023-06-07 22:06 UTC
Labels: priority:P0

**Comment by mwestphal** [comment] 2023-06-08 04:48
Thanks for checking, however how does that work in CI ?

**Comment by Meakk** [comment] 2023-06-08 05:03
I guess Mesa considers `pow(0,0)` is 0 while nvidia considers it's NaN
