### ISSUE TITLE
Loading files from gvfs volumes fails invisibly

### ISSUE THREAD

**Issue by mqudsi** [f3d-app/f3d#1044] opened 2023-10-06 18:55 UTC
**Describe the bug**

f3d fails to load any files from a gvfs-mounted volume.

**To Reproduce**

 0. Mount a folder via gvfs under a gnome-based Linux distribution; for example, under Ubuntu 23.04, mount an SMB folder containing an stl file and then attempt to open that path with `f3d`.
 1. Open the file using `f3d --dry-run  "/run/user/1000/gvfs/smb-share:server=freebsd.local,share=general/cnc/Pill Bottle Cap/Normal Cap v7.stl"`
 2. f3d opens, looks like everything is fine, but no file is loaded. If the command was executed from the terminal, the following output is logged to stderr:
 ```
File /run/user/1000/gvfs/smb-share:server=freebsd.local does not exist
File /home/mqudsi/share=general/cnc/Pill Bottle Cap/Normal Cap v7.stl does not exist
```

**Expected behavior**

f3d should actually succeed in opening the file

**System Information:**
 - OS: Ubuntu 23.04
 - GPU and GPU driver: N/A

**F3D Information**
Paste the content of `f3d --version`:

```
f3d 1.3.1

F3D - A fast and minimalist 3D viewer
Version: 1.3.1.
Build date: 2022-11-06 13:17:51.
Build system: Linux.
Compiler: GNU 12.2.0.
External rendering module: OFF.
Raytracing module: OFF.
Exodus module: ON.
OpenCASCADE module: 7.6.3 (full support).
Assimp module: 5.2.4.
Alembic module: OFF.
VTK version: 9.1.0 (build 0).
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2022 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.
```

**Additional context**

Regular Linux apps can see the file without taking any special actions to account for gvfs file path:

```
mqudsi@ZBook ~> file "/run/user/1000/gvfs/smb-share:server=freebsd.local,share=general/cnc/Pill Bottle Cap/Normal Cap v7.stl"
/run/user/1000/gvfs/smb-share:server=freebsd.local,share=general/cnc/Pill Bottle Cap/Normal Cap v7.stl: data
mqudsi@ZBook ~> f3d "/run/user/1000/gvfs/smb-share:server=freebsd.local,share=general/cnc/Pill Bottle Cap/Normal Cap v7.stl"
File /run/user/1000/gvfs/smb-share:server=freebsd.local does not exist
File /home/mqudsi/share=general/cnc/Pill Bottle Cap/Normal Cap v7.stl does not exist
```

**Comment by mwestphal** [comment] 2023-10-08 17:06
I've yet to test on a gvfs volume but even simple special path like `~/file.ext` are not supported, to be investigated and fixed.

**Comment by mwestphal** [comment] 2023-10-08 17:07
https://github.com/f3d-app/f3d/issues/1042

**Comment by mwestphal** [comment] 2023-10-08 17:25
nevermind, `~/file.ext`  works fine. 

In our case, the `,` means that cxxopts parse it as two separate arguments. Sadly there is no fix yet, but the issue is logged in their repo already: https://github.com/jarro2783/cxxopts/issues/228

**Comment by mwestphal** [comment] 2023-10-08 17:29
Of course, a workaround on your side will be to create a symbolink link to this gvfs folder somewhere, but you probably already know that. Leaving this open until upstream fixes it (or we switch to another framework for handling options, see #434 )

**Comment by Meakk** [comment] 2023-10-08 17:48
I don't think `f3d ~/file.ext` works. It's probably expanded by your shell before reaching f3d.  
If you try `f3d "~/file.ext"` I don't think it works.

**Comment by mwestphal** [comment] 2023-10-09 06:24
Correct, but that is another issue: https://github.com/f3d-app/f3d/issues/1042

Let's open it again

**Comment by mwestphal** [comment] 2023-12-03 09:13
@snoyer this is now fixed right ?

**Comment by mwestphal** [comment] 2023-12-03 11:45
I agree. @mqudsi , please test again with the last nightly:
https://github.com/f3d-app/f3d/releases/tag/nightly

**Closed by mwestphal** 2023-12-03 11:45 UTC
Labels: type:bug
