### ISSUE TITLE
change source code and rebuild pyd file not work

### ISSUE THREAD

**Issue by GitCodeBoy** [f3d-app/f3d#420] opened 2022-09-09 10:31 UTC
**Describe the bug**
I open image.cxx and edit the save method to test:

```
void image::save(const std::string& path) const
{
  auto importer = this->Internals->GetVTKImporter();

  vtkNew<vtkPNGWriter> writer;
  writer->SetFileName(path.c_str());
  writer->SetInputConnection(importer->GetOutputPort());
  writer->Write();
  throw write_exception(" error code"+ std::to_string(writer->GetErrorCode()));
  if (writer->GetErrorCode() != 0)
  {
    throw write_exception("Cannot write " + path;
  }
}
```

And rebuild a new pyd file to replace the origin one,but I find that I can use save method as usual.Any of My changes of code cant effect the pyd file.

Am I missing any steps

**To Reproduce**
 1.edit the image::save method like upon code
 2. rebuild the project (release)
 3. replace origin pyd file
 4. use save method  to test

**Expected behavior**
Throw a runtimeerror

**System Information:**
 - OS: Windows10

**Comment by Meakk** [comment] 2022-09-09 12:38
Sorry I cannot reproduce, a `RuntimeError` containing `error code0` is returned on my side.  
You have a missing parenthesis here: `throw write_exception("Cannot write " + path; // <----`, maybe your compilation is failing?

**Comment by GitCodeBoy** [comment] 2022-09-13 08:42
> Sorry I cannot reproduce, a `RuntimeError` containing `error code0` is returned on my side. You have a missing parenthesis here: `throw write_exception("Cannot write " + path; // <----`, maybe your compilation is failing?

I miss the parenthesis when copy and paste,but I do clear the output directory,and replace the pyd file in my site-packages folder.
`
if __name__ == '__main__':
    import f3d

    engine = f3d.engine(f3d.window.NATIVE)
    window:f3d.window = engine.getWindow()
    interactor:f3d.interactor = engine.getInteractor()
    loader:f3d.loader = engine.getLoader()

    image:f3d.image = window.renderToImage()
    image.save(r"D:/testfile.png")
    interactor.start()
`

when I use configure in "debug" type,save method print valueError:bad conversion.when I use "release" type, the save method generate a png in D:/testfile.png,but it should returned an error.

**Comment by mwestphal** [comment] 2022-09-15 15:07
without answer from @GitCodeBoy , Ill go ahead and close this. Feel free to reopen @GitCodeBoy .

**Closed by mwestphal** 2022-09-15 15:07 UTC
Labels: bug, question
