### ISSUE TITLE
Wrong computation of clip planes when specifying the camera position with certain datasets

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#108] opened 2021-12-05 13:21 UTC
**Describe the bug**
Clipping planes are wrongly computed with large dataset when specyfying the camera positiong
![a](https://user-images.githubusercontent.com/3129530/144748193-9b5e2c19-f547-47ae-8780-e7a4342f9e94.png)

**To Reproduce**
 0. https://sketchfab.com/3d-models/sea-keep-lonely-watcher-09a15a0c14cb4accaf060a92bc70413d#download
 1. Open the file using `f3d source/Stronghold.fbx  --camera-position=7.32912,363.741,1003.36`
 2. nothing appears
 3. move the camera
 4. rendering appears

**Expected behavior**
Correct rendering, like this:
![a](https://user-images.githubusercontent.com/3129530/144748252-927a9cad-ce60-45b0-8929-81e023423db0.png)

**System Information:**
 - OS: ArchLinux
 - GPU and GPU driver: Intel chipset

**F3D Information**
Paste the content of `f3d --version`:

```
[glow@violet ~/Downloads/models/sea]$ ~/Downloads/f3d-1.2.0-Linux/bin/f3d --version                                                       
f3d 1.2.0

F3D - A fast and minimalist 3D viewer
Version: 1.2.0
Build date: 2021-12-04 19:23:10
System: Linux-5.11.0-1021-azure x86_64
Compiler: GNU 7.5.0
RayTracing module: OFF
Exodus module: ON
OpenCASCADE module: 7.6.0 (no metadata)
Assimp module: 5.1.0
VTK version: 9.1.20211124 (build 20211124)

Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2022 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
Written by Michael Migliore, Mathieu Westphal and Joachim Pouderoux.
```

**Additional context**

**Comment by mwestphal** [comment] 2021-12-05 13:21
FYI @Meakk

**Comment by schuhumi** [comment] 2021-12-13 23:20
I have a problem with wrong clipping planes as well. This is the desired result, that shows up when I move the view or zoom in/out
![Bildschirmfoto vom 2021-12-13 23-43-28](https://user-images.githubusercontent.com/5825985/145901001-314a31bf-ba56-4c7c-9220-6ec6516bc388.png)

This is what it looks like upon opening though:
![Bildschirmfoto vom 2021-12-13 23-43-16](https://user-images.githubusercontent.com/5825985/145901113-e236d04c-eca2-43bf-9476-b282a6821155.png)

To cater for https://github.com/f3d-app/f3d/commit/c24e6006b6f50e0a4b4faab5ad444cbb8a9430ad, which is supposed to close this issue as far as I understand, I built from master (as of commit https://github.com/f3d-app/f3d/commit/10208aeb88054ce3cf0e44a030080d711373297a ):

```
> f3d --version
f3d 1.2.1

F3D - A fast and minimalist 3D viewer
Version: 1.2.1
Build date: 2021-12-13 23:31:25
System: Linux-5.15.7-arch1-1 x86_64
Compiler: GNU 11.1.0
RayTracing module: ON
Exodus module: ON
OpenCASCADE module: 7.5.3 (full support)
Assimp module: 5.1.0
VTK version: 9.1.0 (build 0)

Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2022 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
Written by Michael Migliore, Mathieu Westphal and Joachim Pouderoux.
```

I run f3d via 
```
f3d --config=f3d.json erythrocyte2_.obj
```
where f3d.json holds the following content, but passing those options as arguments yields the same result:
```json
{
	".*": {
		"camera-position": "0,0,39",
		"camera-focal-point": "0,0,0",
		"camera-view-up": "1,0,0",
		"camera-view-angle": 20,
		"resolution": "600,600",
	},
}
```

Here you find the .obj and .mtl for reproducibility: [erythrocyte2.zip](https://github.com/f3d-app/f3d/files/7707514/erythrocyte2.zip) It would be nice if this could be fixed, because this breaks rendering into .png for me, which I use f3d for. Of course I can help troubleshoot if you point out where to look for a potential bug

**Comment by Meakk** [comment] 2021-12-14 08:09
@schuhumi I think you issue is unrelated to clipping plane because OBJ files are not affected (because the format does not support transformation).  
Maybe you are experiencing issues because your material is translucent. Try to enable the depth peeling option (`-p`).

**Comment by Meakk** [comment] 2021-12-14 08:20
@schuhumi nevermind, I reproduce your issue, I will investigate.

**Comment by Meakk** [comment] 2021-12-14 08:24
You probably need to call `this->ResetCameraClippingRange();` at the beginning of `vtkF3DRenderer::InitializeCamera()`.  
Can you test and submit a PR if it works?

**Comment by schuhumi** [comment] 2021-12-14 10:43
@Meakk Thank you so much for that speedy and helpful reply!! Yes this mitigates the issue, I created the pull request. Also thank you - and everyone else here for that matter - for working on such an awesome project :)

**Closed** 2021-12-15 10:50 UTC
Labels: bug
