### ISSUE TITLE
Application fails when has to generate thumbnail for certain 3mf file because of a crash on exit

### ISSUE THREAD

**Issue by ByPS128** [f3d-app/f3d#1301] opened 2024-03-05 11:04 UTC
**Describe the bug**
Installed on Windows 11.
I installed the app with the option to create thumbnails. There are 3mf files in the directory that are created by Prusa Slicer 2.6.x and 2.7.x applications.
File Explorer spins the loading wheel icon in the upper left for a while, when refreshing the contents of the directory window (F5 key), but the thumbnails for the 3mf files are not created.

Interesting is, if I drop the 3mf file into opened F3D application, the model in 3mf file is shown. It also works in different way: if I click on 3mf file right mouse, select "open with" choose or locate F3D app, then aso application open and show the model with any problem.

I looked in the Windows event log for applications and found the error listings for F3d.exe
This is what one of the listings looks like:
```
Faulting application name: f3d.exe, version: 0.0.0.0, time stamp: 0x65ad7026
Faulting module name: ntdll.dll, version: 10.0.22621.3085, time stamp: 0xbced4b82
Exception code: 0xc0000374
Fault offset: 0x000000000010c7a9
Faulting process ID: 0x0x9A0
Faulting application start time: 0x0x1DA6EE7DEFA4060
Faulting application path: C:\Program Files\F3D\bin\f3d.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: b42b1aee-fc6f-41b1-a803-f709314cb79e
Faulting package full name: 
Faulting package-relative application ID: 
```
The fault offset and exception code are always the same. So it crashes at the same place.

**To Reproduce**
 1. I uninstall the application, restarted computer and installed it again with ability to create thumbnail enabled
 2. open file explorer and navigate to folder with some 3d files including 3mf files
 3. if i am first time at this folder, I see that windows is generating thumbnails. It took a while.
 4. I see that step or stl files now have correct thumbail, but 3mf file not
 5. go to the event viewer calling eventvwr.exe program, navigate to the Windows logs/Applications and see the last error at top of the log
 6. log Ii found includes report about f3d.exe crash.

**Expected behavior**
Expected is to see thumbnails of 3mf files.

**System Information:**
 - OS: Winfdows 11 Pro Version 10.0.22631 Build 22631
 - CPU: Processor AMD Ryzen 9 5900X 12-Core Processor, 3701 Mhz, 12 Core(s), 24 Logical Processor(s)
 - GPU and GPU driver: Name	NVIDIA GeForce GTX 1060 6GB, Driver Version: 31.0.15.4633
 - Installed Drivers
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_866484083fc526af\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_866484083fc526af\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_866484083fc526af\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_866484083fc526af\nvldumdx.dll

**F3D Information**
Paste the content of `f3d --version`:
F3D 2.3.0

F3D - A fast and minimalist 3D viewer
Version: 2.3.0.
Build date: 2024-01-21 19:27:08.
Build system: Windows 64-bits.
Compiler: MSVC 19.37.32826.1.
External rendering module: ON.
Raytracing module: ON.
VTK version: 9.3.0-1702-geb008dfe7b (date: 20240111).
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2024 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.

**Additional context**
3mf files in my case are created in Prusa Slicer, currently I am using the latest version 2.7.2.

this is how looks my folder with sample case. STL and STEP has valid and correct thumbnal, 3MF not.
![image](https://github.com/f3d-app/f3d/assets/44829883/3b5783c4-634d-490e-95db-194ca1b20f3b)

here is screenshot of event log:
![image](https://github.com/f3d-app/f3d/assets/44829883/18838c4b-7a5d-471b-9e07-e66d8f996755)

here is screenshot shown opened 3mf file in F3D app, no problem.
![image](https://github.com/f3d-app/f3d/assets/44829883/7f0d06da-d4a4-40ab-a129-c2c3e9b4488e)

and here is zipped that 3mf file, maybe it help to find the problem.
[calibration-cube.zip](https://github.com/f3d-app/f3d/files/14494221/calibration-cube.zip)

I have a lot of 3mf files and they all have the same problem with thumbnails.

**Comment by Meakk** [comment] 2024-03-05 12:14
I reproduce the issue. Thank you for reporting, I'm adding that to the next release project.

**Comment by ByPS128** [comment] 2024-03-05 12:29
> --output test.png --config=thumbnail --verbose=quiet --resolution 200,200 calibration-cube.3mf

I also tried running the command to generate the test.png and it generated the image without any problems for me as well. Interesting. Maybe the problem is not in generating the image but in saving it? Isn't it possible that the thumbnail cache update is locked at that moment? Or some similar problem?

**Comment by ByPS128** [comment] 2024-03-05 12:33
I tried to create a new directory in which I put only one file, the 3mf one. I wanted to try if the preview would be created if more images were not cached, but still the preview was not created.

**Comment by ByPS128** [comment] 2024-03-05 12:43
I can confirm your 3mf file got the correct preview immediately after extracting it from the archive.

![image](https://github.com/f3d-app/f3d/assets/44829883/8a7599bd-7131-4e30-ae2c-5b7038071381)

My files are created by saving from the slicer. There will probably be a lot of other metadata in the file besides the model(s) that the slicer puts in.

**Comment by ByPS128** [comment] 2024-03-05 12:51
As soon as I open the 3mf in slicer and save as another file, it shows that the saved file is larger and no preview is created.
![image](https://github.com/f3d-app/f3d/assets/44829883/f8fe238c-a2d6-4269-a0c9-ae2b06437aa1)

![image](https://github.com/f3d-app/f3d/assets/44829883/8ffd5360-74bb-4177-9cce-814136d8325e)

The thumbnail will not be created.
![image](https://github.com/f3d-app/f3d/assets/44829883/371e9c93-9c80-4f07-80b4-dc19d6e57d66)

**Comment by Meakk** [comment] 2024-03-05 13:27
The files are very small (~300kB), it's not related.

**Comment by ByPS128** [comment] 2024-03-05 13:37
Some files are quite large, but most are small, under about 500KB.

![image](https://github.com/f3d-app/f3d/assets/44829883/9e3854d5-a751-4bf3-9ff4-f4c35e148e76)

**Comment by mwestphal** [comment] 2024-03-05 16:56
Sounds like the thumbnailers crash on exit then

**Comment by ByPS128** [comment] 2024-03-05 16:58
> Sounds like the thumbnailers crash on exit then

It almost looks like a memory/resource release crash.

**Comment by Meakk** [comment] 2024-03-06 07:10
Now I remember I had crashes on exit for some 3MF files. I'm pretty sure this is an Assimp issue, probably related to this one: https://github.com/assimp/assimp/issues/5328

**Comment by mwestphal** [comment] 2024-03-06 13:16
Indeed:

```
 ./bin/f3d ~/data/tmp/calibration-cube.3mf --output=a.png
free(): invalid size
Aborted (core dumped)
```

**Comment by mwestphal** [comment] 2024-03-06 13:19
Confirmed caused by assimp:

```
(gdb) bt
#0  0x00007ffff74b9e89 in free () from /usr/lib/libc.so.6
#1  0x00007ffff538ff09 in aiScene::~aiScene() () from /usr/lib/libassimp.so.5
#2  0x00007ffff5372fc7 in Assimp::Importer::~Importer() () from /usr/lib/libassimp.so.5
#3  0x00007ffff7d0f0a2 in vtkF3DAssimpImporter::vtkInternals::~vtkInternals (this=0x555557471350, __in_chrg=<optimized out>)
    at /home/glow/dev/f3d/f3d/src/plugins/assimp/module/vtkF3DAssimpImporter.cxx:43
#4  0x00007ffff7d0f0c8 in std::default_delete<vtkF3DAssimpImporter::vtkInternals>::operator() (this=0x555557282eb0, __ptr=0x555557471350) at /usr/include/c++/13.2.1/bits/unique_ptr.h:99
#5  0x00007ffff7d0c832 in std::unique_ptr<vtkF3DAssimpImporter::vtkInternals, std::default_delete<vtkF3DAssimpImporter::vtkInternals> >::~unique_ptr (this=0x555557282eb0, 
    __in_chrg=<optimized out>) at /usr/include/c++/13.2.1/bits/unique_ptr.h:404
#6  0x00007ffff7d01046 in vtkF3DAssimpImporter::~vtkF3DAssimpImporter (this=0x555557282e20, __in_chrg=<optimized out>)
    at /home/glow/dev/f3d/f3d/src/plugins/assimp/module/vtkF3DAssimpImporter.cxx:891
#7  0x00007ffff7d0107e in vtkF3DAssimpImporter::~vtkF3DAssimpImporter (this=0x555557282e20, __in_chrg=<optimized out>)
    at /home/glow/dev/f3d/f3d/src/plugins/assimp/module/vtkF3DAssimpImporter.cxx:891

```

**Comment by mwestphal** [comment] 2024-03-06 13:27
Fixed in assimp master already, updating assimp on the next release should fix it:
https://github.com/assimp/assimp/pull/5361

**Comment by mwestphal** [comment] 2024-03-10 12:08
So lets wait for their next minor release to close this: https://github.com/assimp/assimp/discussions/5489

**Comment by Aapenootjes** [comment] 2024-04-08 16:59
> So lets wait for their next minor release to close this: [assimp/assimp#5489](https://github.com/assimp/assimp/discussions/5489)

They just released 5.4.0 last night.

**Comment by mwestphal** [comment] 2024-04-23 06:28
Hi @Aapenootjes 

So we just updated assimp in our build system here: https://github.com/f3d-app/f3d-superbuild/pull/167

So you should be able to use our binary nightly release and it should work out of the box!

https://github.com/f3d-app/f3d/releases/tag/nightly

**Closed by mwestphal** 2024-04-23 06:28 UTC
Labels: type:bug, source:assimp

**Comment by ByPS128** [comment] 2024-04-23 15:17
> Hi @Aapenootjes @ByPS128

Hi,
I tried tonight's build and it's a blast. all the files that didn't generate previews are now generating and I think it's even faster.
Great work, thanks a lot.

I noticed that you can also do gcode ;)
