### ISSUE TITLE
Segfault while loading a glTF with a normal map

### ISSUE THREAD

**Issue by SamuelTS** [f3d-app/f3d#188] opened 2022-01-07 17:53 UTC
Hello, I'm unable to load a glTF model with a normal map in F3D v1.2.1.
 
`f3d --input='trex_s.gltf'` gives:

```
ERROR: In /__w/f3d/f3d/dependencies/vtk/Rendering/OpenGL2/vtkShaderProgram.cxx, line 437
vtkShaderProgram (0x55ac9ed42f70): 1: #version 150
2: #ifndef GL_ES
3: #define highp
4: #define mediump
5: #define lowp
6: #endif // GL_ES
7: #define attribute in
8: #define varying out
9: 
10: 
11: /*=========================================================================
12: 
13:   Program:   Visualization Toolkit
14:   Module:    vtkPolyDataVS.glsl
15: 
16:   Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
17:   All rights reserved.
18:   See Copyright.txt or http://www.kitware.com/Copyright.htm for details.
19: 
20:      This software is distributed WITHOUT ANY WARRANTY; without even
21:      the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
22:      PURPOSE.  See the above copyright notice for more information.
23: 
24: =========================================================================*/
25: 
26: in vec4 vertexMC;
27: 
28: 
29: 
30: 
31: // frag position in VC
32: out vec4 vertexVCVSOutput;
33: 
34: // optional normal declaration
35: //VTK::Normal::Dec
36: 
37: // extra lighting parameters
38: //VTK::Light::Dec
39: 
40: // Texture coordinates
41: in vec2 tcoord;
42: out vec2 tcoordVCVSOutput;
43: 
44: uniform mat4 tcMatrix;
45: 
46: // material property values
47: //VTK::Color::Dec
48: 
49: // clipping plane vars
50: //VTK::Clip::Dec
51: 
52: // camera and actor matrix values
53: uniform mat4 MCDCMatrix;
54: uniform mat4 MCVCMatrix;
55: 
56: // Apple Bug
57: //VTK::PrimID::Dec
58: 
59: // Value raster
60: //VTK::ValuePass::Dec
61: 
62: // picking support
63: //VTK::Picking::Dec
64: 
65: void main()
66: {
67:   
68: 
69:   //VTK::Color::Impl
70: 
71:     tangentVCVSOutput = tangentMC;
72:   tangentVCVSOutput = normalMatrix * tangentVCVSOutput;
73: 
74: 
75:   vec4 tcoordTmp = tcMatrix*vec4(tcoord,0.0,1.0);
76: tcoordVCVSOutput = tcoordTmp.xy/tcoordTmp.w;
77: 
78: 
79:   //VTK::Clip::Impl
80: 
81:   //VTK::PrimID::Impl
82: 
83:     vec4 posMC = vertexMC;
84:   gl_Position = MCDCMatrix * posMC;
85:   vertexVCVSOutput = MCVCMatrix * posMC;
86: 
87: 
88:   //VTK::ValuePass::Impl
89: 
90:   //VTK::Light::Impl
91: 
92:   //VTK::Picking::Impl
93: 
94:   //VTK::CustomEnd::Impl
95: }

ERROR: In /__w/f3d/f3d/dependencies/vtk/Rendering/OpenGL2/vtkShaderProgram.cxx, line 438
vtkShaderProgram (0x55ac9ed42f70): 0(71) : error C1503: undefined variable "tangentVCVSOutput"
0(71) : error C1503: undefined variable "tangentMC"
0(72) : error C1503: undefined variable "tangentVCVSOutput"
0(72) : error C1503: undefined variable "normalMatrix"
0(72) : error C1503: undefined variable "tangentVCVSOutput"
```

However [attached model](https://github.com/f3d-app/f3d/files/7830443/trex_s_model.zip) is valid and loads on [glTF Report](https://gltf.report/).

![trex_s_report](https://user-images.githubusercontent.com/36248671/148585683-ffcf97be-8dea-4e81-bb5d-afad87f719bc.png)

**Comment by mwestphal** [comment] 2022-01-07 18:15
I reproduce.

**Comment by Meakk** [comment] 2022-01-07 18:59
Your data contains only `POSITION` and `TEXCOORD_0`, however there is a normal texture.  
In order to display properly a normal mapping, we need `NORMAL` and `TANGENT` attributes.  
`TANGENT` is computed automatically is not provided, but `NORMAL` is expected by VTK / F3D.  

Please, refer to this part in the specification:

> When tangents are not specified, client implementations SHOULD calculate tangents using default MikkTSpace algorithms with the specified vertex positions, normals, and texture coordinates associated with the normal texture.
> 
> When normals are not specified, client implementations MUST calculate flat normals and the provided tangents (if present) MUST be ignored.

However, it's not clear to me what we are supposed to do if a `normalTexture` is specified with no `NORMAL`.  
This is the first time I encounter this case.  
We can:  

1. Compute the normals based on triangle adjacency
2. Ignore the `normalTex` is no `NORMAL` attribute is present

I would choose solution 2 since it's an easy fix.

**Comment by SamuelTS** [comment] 2022-01-07 19:32
Since this glTF model is considered as valid, I would prefer solution 2 even if I have to wait 😅

**Comment by SamuelTS** [comment] 2022-01-07 19:33
Since this model is considered as valid, I would prefer solution 1 even if I have to wait 😅

**Comment by Meakk** [comment] 2022-01-07 21:09
I fixed the issue at the VTK level here: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/8797

![trex](https://user-images.githubusercontent.com/6069752/148606744-b791ed64-0557-41fe-b935-508c9cc555ca.png)

**Comment by SamuelTS** [comment] 2022-01-07 22:10
@Meakk Thanks a lot!

**Comment by mwestphal** [comment] 2022-01-09 07:37
VTK merged.

**Comment by mwestphal** [comment] 2022-01-09 10:59
@SamuelTS : How do you use F3D ? By compiling yourself or using our binary release ? On Which OS ?

**Closed** 2022-01-09 12:07 UTC
Labels: bug, VTK

**Comment by SamuelTS** [comment] 2022-01-09 20:55
@mwestphal I use F3D in CLI mode. For now, I use your binary releases but I wish to compile myself binary for Windows and macOS with Ray Tracing module enabled 🙂

**Comment by mwestphal** [comment] 2022-01-09 21:03
ok.

We have have fixed the issue. Here is a binary nightly release for windows and mac with the fix:

windows: [f3d-windows-latest-e6e10357dc.zip](https://github.com/f3d-app/f3d/files/7835929/f3d-windows-latest-e6e10357dc.zip)
mac: [f3d-macos-latest-e6e10357dc.zip](https://github.com/f3d-app/f3d/files/7835928/f3d-macos-latest-e6e10357dc.zip)
