### ISSUE TITLE
F3D Crashes at startup

### ISSUE THREAD

**Issue by dksmsm** [f3d-app/f3d#169] opened 2021-12-16 23:20 UTC
**Describe the bug**
F3D Crashes at startup

**To Reproduce**
 1. Install F3D from latest .deb package
 2. Run F3D from terminal
 3. The following error message is displayed:

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
ERROR: In /__w/f3d/f3d/dependencies/vtk/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 651
vtkXOpenGLRenderWindow (0x558df22959f0): Cannot create GLX context. Aborting.



Aborted (core dumped)
```

**Expected behavior**
Not crash.

**System Information:**
 - OS: Linux Mint 20.2 Cinnamon
 - GPU and GPU driver: Intel 3rd Gen Core processor Graphics Controller (Integral laptop graphics) + GeForce 710M laptop GPU

**F3D Information**
Paste the content of `f3d --version`:
```
f3d 1.2.1

F3D - A fast and minimalist 3D viewer
Version: 1.2.1
Build date: 2021-12-13 23:27:53
System: Linux-5.11.0-1022-azure x86_64
Compiler: GNU 7.5.0
RayTracing module: OFF
Exodus module: ON
OpenCASCADE module: 7.6.0 (no metadata)
Assimp module: 5.1.0
VTK version: 9.1.20211124 (build 20211124)

Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2022 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
Written by Michael Migliore, Mathieu Westphal and Joachim Pouderoux.
```

**Comment by mwestphal** [comment] 2021-12-17 09:10
Thanks for the report @dksmsm !

This is probably a missing driver on your system (that we should add in the .deb in the future), can you try what is suggested here: https://forums.linuxmint.com/viewtopic.php?t=325046

If that does not work, please open a terminal and give us the output of :+1: 

```
glxinfo
ldd /usr/bin/f3d
ldd /usr/lib/libf3d.so
```

**Comment by dksmsm** [comment] 2021-12-18 00:37
glxinfo:
```

name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
server glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_multisample, GLX_EXT_buffer_age, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_stereo_tree, GLX_EXT_swap_control, 
    GLX_EXT_swap_control_tear, GLX_EXT_texture_from_pixmap, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_NV_delay_before_swap, 
    GLX_NV_float_buffer, GLX_NV_multisample_coverage, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGI_swap_control, GLX_SGI_video_sync
client glx vendor string: NVIDIA Corporation
client glx version string: 1.4
client glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_get_proc_address, GLX_ARB_multisample, GLX_EXT_buffer_age, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_stereo_tree, GLX_EXT_swap_control, 
    GLX_EXT_swap_control_tear, GLX_EXT_texture_from_pixmap, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_NV_copy_image, 
    GLX_NV_delay_before_swap, GLX_NV_float_buffer, 
    GLX_NV_multisample_coverage, GLX_NV_present_video, GLX_NV_swap_group, 
    GLX_NV_video_capture, GLX_NV_video_out, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGI_swap_control, GLX_SGI_video_sync
GLX version: 1.4
GLX extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_get_proc_address, GLX_ARB_multisample, GLX_EXT_buffer_age, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_stereo_tree, GLX_EXT_swap_control, 
    GLX_EXT_swap_control_tear, GLX_EXT_texture_from_pixmap, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_NV_delay_before_swap, 
    GLX_NV_float_buffer, GLX_NV_multisample_coverage, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGI_swap_control, GLX_SGI_video_sync
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2048 MB
    Total available memory: 2048 MB
    Currently available dedicated video memory: 1804 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce 710M/PCIe/SSE2
OpenGL core profile version string: 4.4.0 NVIDIA 340.108
OpenGL core profile shading language version string: 4.40 NVIDIA via Cg compiler
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

[...]

```
Full output: [glxinfo.txt](https://github.com/f3d-app/f3d/files/7738347/glxinfo.txt)

ldd /usr/bin/f3d

```
        linux-vdso.so.1 (0x00007ffd0fbf6000)
	libf3d.so => /usr/bin/../lib/libf3d.so (0x00007f48d123d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f48d11f3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f48d11d0000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f48d0fee000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f48d0fd3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f48d0de1000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f48d0ca2000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f48d0c6e000)
	libOpenGL.so.0 => /usr/lib/x86_64-linux-gnu/libOpenGL.so.0 (0x00007f48d0c42000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f48d0c37000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f48d0ae8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f48d56bb000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f48d0abc000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f48d0a04000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f48d09fe000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f48d09f6000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f48d09dc000)


```

ldd /usr/lib/libf3d.so

```
	linux-vdso.so.1 (0x00007ffcfafa3000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f86eda72000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f86eda3e000)
	libOpenGL.so.0 => /usr/lib/x86_64-linux-gnu/libOpenGL.so.0 (0x00007f86eda12000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f86eda0c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f86ed9e9000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f86ed9de000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f86ed7fa000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f86ed6ab000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f86ed690000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f86ed49e000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f86ed474000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f86ed3bc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f86f1e29000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f86ed3b4000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f86ed3ac000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f86ed392000)
```


**LIBGL_DEBUG=verbose** glxgears
        `5007 frames in 5.0 seconds = 1001.217 FPS`
(no errors)

**LIBGL_DEBUG=verbose** f3d

```
libGL: screen 0 does not appear to be DRI2 capable
libGL: MESA-LOADER: dlopen(/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
ERROR: In /__w/f3d/f3d/dependencies/vtk/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 651
vtkXOpenGLRenderWindow (0x55d26b7d29f0): Cannot create GLX context.  Aborting.


Aborted (core dumped)
```
sudo find /usr -iname "*libGL.so*" -exec ls -l -- {} + 

```
lrwxrwxrwx 1 root root      10 Apr 29  2021 /usr/lib/i386-linux-gnu/libGL.so -> libGL.so.1
lrwxrwxrwx 1 root root      16 Apr 29  2021 /usr/lib/i386-linux-gnu/libGL.so.1 -> libGL.so.340.108
-rw-r--r-- 1 root root  439868 Nov 24  2020 /usr/lib/i386-linux-gnu/libGL.so.1.7.0
lrwxrwxrwx 1 root root      14 Nov 24  2020 /usr/lib/i386-linux-gnu/libGL.so.1.distrib -> libGL.so.1.7.0
-rw-r--r-- 1 root root 1075136 Dec 12  2019 /usr/lib/i386-linux-gnu/libGL.so.340.108
lrwxrwxrwx 1 root root      10 Apr 29  2021 /usr/lib/x86_64-linux-gnu/libGL.so -> libGL.so.1
lrwxrwxrwx 1 root root      16 Apr 29  2021 /usr/lib/x86_64-linux-gnu/libGL.so.1 -> libGL.so.340.108
-rw-r--r-- 1 root root  547152 Nov 24  2020 /usr/lib/x86_64-linux-gnu/libGL.so.1.7.0
lrwxrwxrwx 1 root root      14 Nov 24  2020 /usr/lib/x86_64-linux-gnu/libGL.so.1.distrib -> libGL.so.1.7.0
-rw-r--r-- 1 root root 1267800 Dec 12  2019 /usr/lib/x86_64-linux-gnu/libGL.so.340.108
lrwxrwxrwx 1 root root      10 Nov 24  2020 /usr/lib/x86_64-linux-gnu/libGL.so.distrib -> libGL.so.1
-rw-r--r-- 1 root root  264544 Mar  9  2020 /usr/lib/x86_64-linux-gnu/primus/libGL.so.1
```
From the above it seems like my graphics driver is configured correctly (as far as I can tell)

**Comment by mwestphal** [comment] 2021-12-18 07:32
can you try the following:

```
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGL.so.1.7.0 f3d
```

and

```
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGL.so.340.108 f3d
```

Thx

**Comment by dksmsm** [comment] 2021-12-19 03:16
First one didn't work. Second one worked like a charm!

**Comment by mwestphal** [comment] 2021-12-19 11:30
Great ! At least you have a work around !

Let's try to figure out if the issue is on your side or in F3D binary.

please try the following:

```
ldd glxgears
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGL.so.1.7.0 glxgears
```

I expect the second command to fail but not entirely sure.

**Comment by dksmsm** [comment] 2021-12-19 15:04
Didn't work. 

```
~ $ ldd glxgears
ldd: ./glxgears: No such file or director
```

```
~ $ LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGL.so.1.7.0 glxgears
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Error: glXCreateContext failed

```

**Comment by mwestphal** [comment] 2021-12-19 16:07
shoudl have been:

```
ldd /usr/binglxgears
```

In any case, since glxgears cannot use it either , your mesa installation seems faulty. Not a F3D issue imo, so closing this.
I'd suggest reinstalling mesa or just use LD_PRELOAD with F3D.

What is still a bit strange is that F3D use this libGL instead of the one provided by your system, thats usually hndled by your system, but as you mentionned it already, linux + optimus (Chipset + GPU) is always a bit janky.

**Closed by mwestphal** 2021-12-19 16:07 UTC
Labels: bug

**Comment by dksmsm** [comment] 2021-12-23 22:08
Thank you!
